const sharp = require('sharp');
const fs = require('fs');

const inputPath = process.argv[2];
const outputPath = 'processed_image.jpg';

if (!inputPath) {
  console.error('❌ 请提供图片路径: node scripts/edit_image.js <image_path>');
  process.exit(1);
}

async function processImage() {
  try {
    console.log(`🎨 正在处理图片: ${inputPath}...`);
    
    // 获取图片元数据以确定尺寸
    const metadata = await sharp(inputPath).metadata();
    const width = metadata.width;
    const height = metadata.height;

    // 创建一个 SVG 文字水印 (居中，红色，半透明)
    // 字体大小根据图片宽度自适应
    const fontSize = Math.floor(width * 0.05); 
    const svgText = `
      <svg width="${width}" height="${height}">
        <style>
          .title { fill: red; fill-opacity: 0.5; font-size: ${fontSize}px; font-weight: bold; font-family: sans-serif; }
        </style>
        <text x="50%" y="95%" text-anchor="middle" class="title">Generated by Cascade</text>
        <text x="50%" y="50%" text-anchor="middle" class="title" transform="rotate(-45, ${width/2}, ${height/2})">CONFIDENTIAL</text>
      </svg>
    `;

    await sharp(inputPath)
      .composite([
        {
          input: Buffer.from(svgText),
          top: 0,
          left: 0,
        },
      ])
      .toFile(outputPath);

    console.log(`✅ 图片处理完成! 已保存为: ${outputPath}`);
    
  } catch (error) {
    console.error('❌ 图片处理失败:', error.message);
  }
}

processImage();
